// Global styles
import './styles/colors.css'

// Hooks
export {
  useSiwe,
  useChain,
  useIsClient,
  useCoolMode,
  useWindowSize,
  useOutsideClick,
  useTooltipPosition,
  useProfileDetails,
  useGrailsProfile,
} from './hooks'

// Utils
export {
  isAddress,
  formatNumber,
  formatTimeDiff,
  formatQueryParams,
  truncateAddress,
  fetchProfileDetails,
  fetchAccount,
  isLinkValid,
  isValidEnsName,
  createSiweMessageString,
  loadTranslationsFromJSON,
  normalizeEnsName,
  beautifyEnsName,
  validateEnsHeader,
  fetchNameMetadata,
  fetchNameRoles,
  formatNameMetadata,
  formatNameMetadataRecord,
} from './utils'

// Context
export { TranslationProvider, useTranslation } from './context'

// Constants
export {
  GRAILS_API_URL,
  ENS_METADATA_URL,
  DEFAULT_FALLBACK_AVATAR,
  DEFAULT_FALLBACK_HEADER,
  DEFAULT_LOADING_GRADIENT,
  LIGHT_LOADING_GRADIENT,
  THEMES,
  FETCH_LIMIT,
  PROFILE_CARD_SOCIALS,
  chains,
  DEFAULT_CHAIN,
  ChainIcons,
  BLOCK_EXPLORERS,
  ENSContracts,
  PublicResolverAbi,
  BaseRegistrarAbi,
  RegistrarControllerAbi,
  RegistryAbi,
  transports,
  SECOND,
  MINUTE,
  HOUR,
  DAY,
  WEEK,
  MONTH,
  defaultTranslations,
  TEXT_RECORD_KEYS,
  ADDRESS_RECORD_KEYS,
  COIN_TYPES,
  SOCIAL_RECORDS,
  ADDRESS_LABELS,
} from './constants'

// Constant Types
export type { Chain } from './constants/chains'

// Components
export {
  ProfileCard,
  ProfileSocials,
  Avatar,
  LoadingCell,
  HeaderImage,
  ImageWithFallback,
  Bio,
  FullWidthProfile,
  ProfileTooltip,
  SignInButton,
  SignInWithEthereum,
  Input,
  Textarea,
  TabSelector,
  ENSRecords,
  ResolvedInput,
  // Icons
  Check,
  Cross,
  Note,
  Arrow,
  Clock,
  Wallet,
  Refresh,
  Link,
  Ethereum,
  Optimism,
  Base,
  X,
  Discord,
  Telegram,
  Github,
  GithubDark,
  ENS,
  ENSCircle,
  Dweb,
  Etherscan,
  EtherscanDark,
  MapPin,
  Pencil,
  PersonCircle,
  Photo,
  Quotes,
  Reset,
  Trash,
  ShortArrow,
  Person,
  Key,
  Calendar,
  Email,
  MagnifyingGlass,
  EthereumIcon,
  Grails,
  Vision,
  Opensea,
} from './components'

// Component Types
export type {
  ProfileCardProps,
  ProfileSocialsProps,
  AvatarProps,
  LoadingCellProps,
  ImageWithFallbackProps,
  FullWidthProfileProps,
  SignInWithEthereumProps,
  ProfileTooltipProps,
  SignInButtonProps,
  InputProps,
  TextareaProps,
  TabSelectorProps,
  Tab,
  ENSRecordsProps,
} from './components'

// Types
export type {
  SizeType,
  Address,
  Hex,
  ENSProfile,
  ENSMetadataProfile,
  ProfileDetailsResponse,
  AccountResponseType,
  ProfileSocialType,
  TranslationKey,
  TranslationFunction,
  TranslationConfig,
  TranslationsMap,
  TranslationObject,
  LanguageCode,
  GrailsAPIResponse,
  GrailsProfileResponse,
  ENSNameMetadataValue,
  ENSNameMetadataResponse,
  GrailsNameMetadataResponse,
  RolesType,
  GrailsRolesResponse,
} from './types'
